name: Githug-pages
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Ceckout
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
       
    - name: Install dependencies
      run: |
        npm i
        ng build --prod --base-href /angular-self-contained/
        touch ./dist/angular-self-contained/.nojekyll
        
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        target_branch: gh-pages
        build_dir: ./dist/angular/angular-self-contained
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
